### ISSUE TITLE
Support for saving Cmake targets between sessions

### ISSUE THREAD

**Issue by Midren** [ilyachur/cmake4vim#113]
**Is your feature request related to a problem? Please describe.**
I have been using plugins like vim-workspace, vim-session to be able to restore previous work for the current project. But every time the CMake target needs to be set again, so I frequently encounter situations when I build 'all' target. 

**Describe the solution you'd like**
As it was mention by [tpope](https://github.com/tpope/vim-obsession/issues/44#issuecomment-398879095), adding `: set sessionoptions+=globals` can help, but only global variables starting with Upper case is saved, so I propose to change `g:cmake_build_target` to `g:Cmake_build_target` and all other related variables.

**Comment by mark2185** [comment]
Couldn't you just explicitly add `g:cmake_build_target` to [g:session_persist_globals](https://github.com/xolox/vim-session#the-gsession_persist_globals-option)?

**Comment by ilyachur** [comment]
@mark2185 Thank you for advice!
@Midren  Could you use this approach?

Honestly I really don't want to change variables to upper case, it looks like a hack, moreover I cannot do it from the backward compatibility side, guys are using this plugin and I cannot break their pipelines.

**Comment by Midren** [comment]
@mark2185 Currently, switched to the vim-workspace, as vim-session looks abandoned, but I will see, how it can be used.

**Comment by mark2185** [comment]
@Midren if that doesn't suit your needs, I usually have project specific `.vimrc`s that have `let g:cmake_build_target = 'some_target'` and similar things, maybe that'll help.

```
		*'exrc'* *'ex'* *'noexrc'* *'noex'*
'exrc' 'ex'		boolean (default off)
			global
	Enables the reading of .vimrc, .exrc and .gvimrc in the current
	directory.
```

**Comment by ilyachur** [comment]
@DoDoENT @mark2185 Guys, thank you for using the plugin and developing new features.

I kindly ask you if you want to improve or change something, feel free to contribute to the original repo. I am opened for any enhancements. 

Deprecation strategy can be used for changing names of variables.
I think more users will use features if they are a part of this repo 😄

**Comment by mark2185** [comment]
> I kindly ask you if you want to improve or change something, feel free to contribute to the original repo. I am opened for any enhancements.

I will, I think that for the most of the major changes I have opened a PR, but in the meantime I pushed some things into the fork's `master` as it was easier to allow my colleagues to test out new things so that's why it's not `1:1`, but I promise I'll clean it up and open up a few PR's for the missing bits :)

**Comment by ilyachur** [comment]
@mark2185 Cool I will wait new PRs from you 😄 

@DoDoENT I propose to have all variables in the same manner. If we need to have variables in CammelCase (from upper case) and it's justified, I propose to rename all variables in order to have one naming style. Because the mix of style looks strange for the end user.
In PR https://github.com/ilyachur/cmake4vim/pull/121 I deprecated some global variables, here we can use the same strategy.
