### ISSUE TITLE
CMakeBuild fails

### ISSUE THREAD

**Issue by BodeSpezial** [ilyachur/cmake4vim#68]
**Describe the bug**
When I try to use `CMakeBuild` I get the error
```
make: *** empty string invalid as file name.  Stop. 
```

**To Reproduce**
1. Create sample project
2. Run `CMake`
3. Run `CMakeBuild`
4. Error

**Expected behavior**
I hoped that it would compile my project so I can compile it from inside of vim (build on save sounds very promising)

**Screenshots**
Video attached:
https://user-images.githubusercontent.com/46973479/103158416-d998e880-47bd-11eb-95d7-7e38661f0a5c.mov

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Editor vim
 - Version 8.1.2292
 - Terminal Emulator: iTerm 3.4.3
 - Shell: fish 3.1.2

**Additional context**

**Comment by ilyachur** [comment]
Hi @BodeSpezial,

Thank you for the issue. But I cannot reproduce it.
`:CMakeBuild` works always for me. I tried to make the same project but it works.

Didn't you set any environment or plugin variables?
Could you please provide information from `:CMakeInfo` command?

- Run `:Cmake`
- Run `:CMakeInfo`

For the same project I got the next CMake information:
```
CMake:
    version:            3.19.0

Project:
    name:               test
    build type:         Release
    build directory:    /tmp/test/cmake-build-Release
    generator:          Unix Makefiles
    generation command: cmake -DCMAKE_BUILD_TYPE=Release  -B /tmp/test/cmake-build-Release -S /tmp/test
    build command:      cmake --build /tmp/test/cmake-build-Release --target all -- 
```

**Comment by BodeSpezial** [comment]
Hi @ilyachur
By now I set the reload on save variable for the `CMakeLists.txt`. But that didn't change anything.
I mean.. I have some environment variables defined but I couldn't think of anything specific for cmake or make. 

Here is my `CMakeInfo`:

```
​CMake:
    version:            3.18.4

Project:
    name:               test
    build type:         Release
    build directory:    /Users/bode/cmake4vim-issue/build-Release
    generator:          Unix Makefiles
    generation command: cmake -DCMAKE_BUILD_TYPE=Release  -B /Users/bode/cmake4vim-issue/build-Release -S /Users/bode/cmake4vim-issue
    build command:      cmake --build /Users/bode/cmake4vim-issue/build-Release --target all --
```

**Comment by BodeSpezial** [comment]
The strange thing is, that `make` works inside of vim.

**Comment by ilyachur** [comment]
@BodeSpezial I think the problem cannot be solved by setting some plugin variables. I think you have some problems with build process...
If I understand right you are using the `Dispatch`. The plugin only [sets](https://github.com/ilyachur/cmake4vim/blob/master/autoload/utils/exec/dispatch.vim#L10) the `makeprg` variable and run `Dispatch` maybe something wrong here... I cannot reproduce it on my side. I propose to do next experiments:

- Try to don't use dispatch (You can use `g:cmake_build_executor` variable in order to change executor).
- Could you run build from vim: `:!cmake --build /Users/bode/cmake4vim-issue/build-Release --target all --`?
- Try to change `makeprg` variable and run dispatch manually
```
:let &l:makeprg = ...
:Make
```
- If the problem is related with `Dispatch` I propose try to print [here](https://github.com/ilyachur/cmake4vim/blob/master/autoload/utils/exec/dispatch.vim#L13) the value of `l:makeprg` variable.

Can you try to do these things?

**Comment by BodeSpezial** [comment]
I never wrote vim plugins by myself but I'm gonna go ahead and try to debug it later.

The files are loaded from the autoload folder inside of my vim folder aren't they?!

**Comment by ilyachur** [comment]
> I never wrote vim plugins by myself but I'm gonna go ahead and try to debug it later.
> 
> The files are loaded from the autoload folder inside of my vim folder aren't they?!

I can help you if you have any questions, it is really interesting why other users and me don't have such issues 😄 
Yes, the plugin core is located in the `autoload` folder. `plugin` folder contains only public API.

**Comment by BodeSpezial** [comment]
Ok.
So if I set the `g:cmake_build_executor="job"` it fails as usual. Same if I do `g:cmake_build_executor="dispatch"` (But given your message that was to expect).
But if I use 'g:cmake_build_executor="system"` it works fine.

Could I ask what those executors are?

**Comment by BodeSpezial** [comment]
Running cmake manually works
The last step confused me a bit.
Should I set the variable to the respective mode I want to try?

**Comment by ilyachur** [comment]
> Ok.
> So if I set the `g:cmake_build_executor="job"` it fails as usual. Same if I do `g:cmake_build_executor="dispatch"` (But given your message that was to expect).
> But if I use 'g:cmake_build_executor="system"` it works fine.
> 
> Could I ask what those executors are?

At the current moment the plugins supports 3 types of executors:

- system - it uses `system` vim command and it allows to run build process syncroniously.
- job - async build run which uses vim jobs
- dispatch - async build which uses `Dispatch` plugin

Am I right that you have this issue for `dispatch` and `job` executors?

> Running cmake manually works

Does it work from vim? Or from the command line?
> The last step confused me a bit.
> Should I set the variable to the respective mode I want to try?

If you are talking about this step:
Try to change makeprg variable and run dispatch manually
...

If yes, I propose to set the variable and run `Dispatch` `Make` command.

> And if I try to echo at line 13 I don't get to see it. I guess it gets replaced by the error.

Maybe you could miss the error message. I propose to use method `utils#common#Warning('message')` in order to print the value of `l:makeprg` variable. In this case if you miss the message, you always will be able to find it in the vim messages (`:message` command).

**Comment by mark2185** [comment]
@BodeSpezial any updates on this?

**Comment by alexames** [comment]
I'm seeing this issue as well, but I have a temporary workaround of questionable quality.

Like others, when I navigate to my project's directory, run `:CMake` and then `:CMakeBuild`, I get the following error:

    ||                                                                                                                                                                                                                                                                        
    || gmake: *** empty string invalid as file name.  Stop.        

When the executor is not specified or set to `'job'` I get that error. If I switch it to `'system'`, it works. (But it's synchronous, which sucks)

Looking over the documentation for `job_start`, it mentions that strings are passed to execvp. I don't know anything about what that means other than it seems to be related to how strings are split up I guess. The docs for `job_start` mention that you can optionally pass it a list instead of a string, so I tried running it that way, and that appears to work!

So as a temporary work around, I've changed line [155 of job.vim](https://github.com/ilyachur/cmake4vim/blob/03eaa97dd12bed2280cac6c05a23bb0c21930bea/autoload/utils/exec/job.vim#L155) to 

    job_start(split(a:cmd), {

I'm not entirely sure what's going wrong - it's got something to do with how `job_start` runs string commands compared to how it runs commands in list form. I'm not convinced this is the right fix (or the right place to put the fix, maybe whatever constructs `a:cmd` should be doing it differently), but at least I've narrowed down what's going wrong.

**Comment by ilyachur** [comment]
@alexames Could you try to change the pipeline to:

```
:CMake
:CMakeSelectTarget all // or any other target
:CMakeBuild
```
Does it works for your case? Or not?

**Comment by mark2185** [comment]
Well I guess this part of the documentation is the best explanation we're going to get:
```
{command} can be a List, where the first item is the executable
and further items are the arguments.  All items are converted
to String.  This works best on Unix.
```

**Comment by alexames** [comment]
@ilyachur 

No, that doesn't appear to make any difference.

**Comment by ilyachur** [comment]
@alexames Ok, thank you!

So, I hope PR https://github.com/ilyachur/cmake4vim/pull/106 should help you.

**Comment by alexames** [comment]
I just tried pulling in #106 and it appears to fix the issue.

**Comment by BodeSpezial** [comment]
@mark2185 Excuse me for not answering. I didn't have to work on C code for a while so I put it aside.
If I recall correctly I chose a different executor and it worked.

**Comment by mark2185** [comment]
> @mark2185 Excuse me for not answering. I didn't have to work on C code for a while so I put it aside.
> If I recall correctly I chose a different executor and it worked.

No problem :)

In any case, it should work with the `job` executor as well when the #106 closes, just a few pesky windows tests and we're all set.
