### ISSUE TITLE
Odd entries in :CMakeSelectTarget and :FZFCMakeSelectTarget

### ISSUE THREAD

**Issue by mark2185** [ilyachur/cmake4vim#90]
**Describe the bug**
In addition to the real targets, I get some other entries that make no sense. When one of those is selected, nothing happens.

**To Reproduce**
Not sure.

**Expected behavior**
Only the targets should appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/8365241/114843722-66ea6200-9dda-11eb-963b-46ea224f7fc9.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Editor vim -  8.2

**Additional context**
I'll look into this at some point, but I'm just opening an issue so I don't forget.

**Comment by ilyachur** [comment]
@mark2185 Do you use Unix Makefiles?
I think the issue is [somewhere here](https://github.com/ilyachur/cmake4vim/blob/master/autoload/utils/gen/make.vim#L24).
Here I have a logic to parse command line output for `cmake --target help` command.
I don't have such problems in my environment, maybe it can depend on version of build tools.

Hmmm, I just thought that for CMake 3.14+ we can use cmake-file-api to get all targets and it should be generator independent.

**Comment by mark2185** [comment]
> @mark2185 Do you use Unix Makefiles?

Nope, `ninja`.

> I think the issue is [somewhere here](https://github.com/ilyachur/cmake4vim/blob/master/autoload/utils/gen/make.vim#L24).
> Here I have a logic to parse command line output for `cmake --target help` command.

It might be because of that, because `help` is one of the targets I get!

> Hmmm, I just thought that for CMake 3.14+ we can use cmake-file-api to get all targets and it should be generator independent.

That would be great! You have more experience with the `cmake` API, but let me know if I can help somehow or if you would like me to take that task.

**Comment by ilyachur** [comment]
I will try to make some experiments, but of older cmake versions we still need to have these parsers for different Generators.

**Comment by ilyachur** [comment]
> For `Ninja`, in `ninja.vim:5` seems to work. I don't know why that message started appearing.

Do you mean the 'All primary targets ...' message? Maybe it depends on Ninja version.

BTW I tried to use targets from cmake-file-api response, but it doesn't look like a 100% replacement for Generator specific handler, because the reply from cmake-file-api doesn't contain service targets (like clean, all, help and etc.).

**Comment by mark2185** [comment]
This seems to be solved, the `All primary targets` part is in `master`.
